export class Persona {
    identificacion:string;
    nombre:string;
    apellido:string;
    sexo:string;
    edad:number;
    estadoCivil:string;
    paisDeProcedencia:string;
    nivelEducativo:string;
    conocimiento1:string;
    conocimiento2:string;
    conocimiento3:string;
    conocimiento4:string;
    conocimiento5:string;
    conocimientoExplicacion:string;
    actitud1:string;
    actitud2:string;
    actitud3:string;
    actitudExplicacion:string;
    actitud5:string;
    actitud6:string;
    practica1:string;
    practica2:string;
    practica3:string;
    practica4:string;
}
